### ISSUE TITLE
"Character-level Convolutional Networks for Text Classification"

### ISSUE THREAD

**Issue by sobamchan** [mhagiwara/100-nlp-papers#1]
First, Thank you for sharing information which is great for NLP leaning students.

Since CNNs has great result in computer vision, researchers started to apply them for NLP tasks.
This paper "Character-level Convolutional Networks for Text Classification" shows the first step for it.
And also I think this paper could be nicer to read with "Very Deep Convolutional Networks for Natural Language Processing"

Thanks

**Comment by mhagiwara** [comment]
Thanks, I added the first paper to the list. I think the second one is still too early to tell since as of now it only has 10 citations. Time will tell :)
